
import java.util.ArrayList;


/**
 *
 * @author Hrithik
 */
public class AirLine extends javax.swing.JFrame {

    /**
     * Creates new form StudentGradesUI
     */
    public AirLine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblfname = new javax.swing.JLabel();
        lbllname = new javax.swing.JLabel();
        fnamein = new javax.swing.JTextField();
        lnamein = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        list = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pointbox = new javax.swing.JTextArea();
        output = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        lblweek1 = new javax.swing.JLabel();
        week1in = new javax.swing.JTextField();
        lblweek2 = new javax.swing.JLabel();
        week2in = new javax.swing.JTextField();
        totalPoints = new javax.swing.JButton();
        lblweek3 = new javax.swing.JLabel();
        week3in = new javax.swing.JTextField();
        lblweek4 = new javax.swing.JLabel();
        week4in = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblfname.setText("First Name:");

        lbllname.setText("Last Name:");

        fnamein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameinActionPerformed(evt);
            }
        });

        lnamein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameinActionPerformed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        list.setText("List");
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        pointbox.setColumns(20);
        pointbox.setRows(5);
        jScrollPane1.setViewportView(pointbox);

        title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        title.setText("AirLine Points");

        lblweek1.setText("Week 1:");

        week1in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                week1inActionPerformed(evt);
            }
        });

        lblweek2.setText("Week 2:");

        week2in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                week2inActionPerformed(evt);
            }
        });

        totalPoints.setText("Total Points");
        totalPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPointsActionPerformed(evt);
            }
        });

        lblweek3.setText("Week 3:");

        week3in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                week3inActionPerformed(evt);
            }
        });

        lblweek4.setText("Week 4:");

        week4in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                week4inActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblweek1)
                                .addComponent(lblweek2)
                                .addComponent(lblweek3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblweek4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(week2in, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(week3in, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(totalPoints))
                                        .addComponent(week4in, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(87, 87, 87))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(week1in, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(list)
                                        .addComponent(add))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(title)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblfname)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fnamein, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbllname)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lnamein, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnamein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllname)
                    .addComponent(lnamein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblweek1)
                    .addComponent(week1in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblweek2)
                        .addComponent(week2in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblweek3)
                    .addComponent(week3in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPoints))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblweek4)
                    .addComponent(week4in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void fnameinActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void lnameinActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    // create arraylist for employee names
    ArrayList<String> names = new ArrayList<String>();
    // create arraylist of arraylists for data
    ArrayList<ArrayList<Integer>> points = new ArrayList<ArrayList<Integer>>();
    // counter
    int count = 0;   
    private void addActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        
        // get all inputs and store in variable
        int week1 = Integer.parseInt (week1in.getText ());
        int week2 = Integer.parseInt (week2in.getText ());
        int week3 = Integer.parseInt (week3in.getText ());
        int week4 = Integer.parseInt (week4in.getText ());
        String fname = fnamein.getText ();
        String lname = lnamein.getText ();
        
        names.add (fname +" "+ lname);
        points.add (new ArrayList<Integer>());
        points.get (count).add (week1);
        points.get (count).add (week2);
        points.get (count).add (week3);
        points.get (count).add (week4);
        count++;
        output.setText ("Points have been added to "+fname+"'s account.");
        // reset
        week1in.setText ("");
        week2in.setText ("");
        fnamein.setText ("");
        lnamein.setText ("");
        week3in.setText ("");
        week4in.setText ("");
    }                                   

    private void listActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
      // reset
        pointbox.setText ("");
        output.setText ("");
        // list out
        for (int i = 0; i < names.size (); i++)
        {
            //pointbox.append (names.get(i)+" "+points.get (i).get (0)+" "+points.get (i).get(1)+" "+points.get (i).get(2)+" "+points.get(i).get(3)+"\n");
            pointbox.append ("Name: "+names.get(i)+"\nWeek 1: "+points.get (i).get (0)+"\nWeek 2: "+points.get (i).get(1)+"\nWeek 3: "+points.get (i).get(2)+"\nWeek 4: "+ points.get (i).get (3)+"\n\n");
        }
    }                                    

    private void week1inActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void week2inActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void totalPointsActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String firstname = fnamein.getText ();
        String lastname = lnamein.getText ();
        String fullname = firstname + " " + lastname;
        int sum = 0, points1 = 0, points2 = 0, points3 = 0, points4 = 0, bonus = 0;
        
        for (int i = 0; i < names.size (); i++)
        {
          if (names.get (i).equals (fullname)) // check if in the arraylist
          {
             points1 = points.get (i).get (0);
             points2 = points.get (i).get (1);
             points3 = points.get (i).get (2);
             points4 = points.get (i).get (3);
             sum = points1 + points2 + points3 + points4; // add up all points
             if (sum > 5000)
             {
               bonus = 1000;
             }
             output.setText (fullname+"'s Total points are: "+sum+" Bonus: "+bonus);
             break;
          }
          else
          {
            output.setText ("The name you have entered is not in our databases.");
          }
        }
    }                                           

    private void week3inActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void week4inActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGradesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGradesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGradesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGradesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirLine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton add;
    private javax.swing.JTextField fnamein;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblweek1;
    private javax.swing.JLabel lblweek2;
    private javax.swing.JLabel lblweek3;
    private javax.swing.JLabel lblweek4;
    private javax.swing.JButton list;
    private javax.swing.JTextField lnamein;
    private javax.swing.JTextField output;
    private javax.swing.JTextArea pointbox;
    private javax.swing.JLabel title;
    private javax.swing.JButton totalPoints;
    private javax.swing.JTextField week1in;
    private javax.swing.JTextField week2in;
    private javax.swing.JTextField week3in;
    private javax.swing.JTextField week4in;
    // End of variables declaration                   
}
