
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saksham
 */
public class PlayerSelectApp extends javax.swing.JFrame {

    /**
     * Creates new form PlayerSelectApp
     */
    public PlayerSelectApp() {
	initComponents();
    }
    
    static int playerCount = 0;
    static ArrayList<Player> tempPlayers = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	numPlayers = new javax.swing.ButtonGroup();
	lblPlayers = new javax.swing.JLabel();
	rdBtn2 = new javax.swing.JRadioButton();
	rdBtn3 = new javax.swing.JRadioButton();
	rdBtn4 = new javax.swing.JRadioButton();
	lblName = new javax.swing.JLabel();
	lblPlayerName1 = new javax.swing.JLabel();
	lblPlayerName2 = new javax.swing.JLabel();
	lblPlayerName3 = new javax.swing.JLabel();
	lblPlayerName4 = new javax.swing.JLabel();
	txtPlayer1 = new javax.swing.JTextField();
	txtPlayer2 = new javax.swing.JTextField();
	txtPlayer3 = new javax.swing.JTextField();
	txtPlayer4 = new javax.swing.JTextField();
	btnConfirm = new javax.swing.JButton();

	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

	lblPlayers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	lblPlayers.setText("How many players?");

	numPlayers.add(rdBtn2);
	rdBtn2.setText("2");
	rdBtn2.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		rdBtn2ActionPerformed(evt);
	    }
	});

	numPlayers.add(rdBtn3);
	rdBtn3.setText("3");
	rdBtn3.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		rdBtn3ActionPerformed(evt);
	    }
	});

	numPlayers.add(rdBtn4);
	rdBtn4.setText("4");
	rdBtn4.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		rdBtn4ActionPerformed(evt);
	    }
	});

	lblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	lblName.setText("Enter each Player's Name:");

	lblPlayerName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	lblPlayerName1.setText("Player 1:");

	lblPlayerName2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	lblPlayerName2.setText("Player 2:");

	lblPlayerName3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	lblPlayerName3.setText("Player 3:");

	lblPlayerName4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	lblPlayerName4.setText("Player 4:");

	txtPlayer1.setEnabled(false);

	txtPlayer2.setEnabled(false);

	txtPlayer3.setEnabled(false);

	txtPlayer4.setEnabled(false);

	btnConfirm.setText("Confirm");
	btnConfirm.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		btnConfirmActionPerformed(evt);
	    }
	});

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(
	    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    .addGroup(layout.createSequentialGroup()
		.addContainerGap()
		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		    .addGroup(layout.createSequentialGroup()
			.addComponent(lblPlayerName1)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
			.addComponent(txtPlayer1))
		    .addGroup(layout.createSequentialGroup()
			.addComponent(lblPlayerName2)
			.addGap(10, 10, 10)
			.addComponent(txtPlayer2))
		    .addGroup(layout.createSequentialGroup()
			.addComponent(lblPlayerName3)
			.addGap(10, 10, 10)
			.addComponent(txtPlayer3))
		    .addGroup(layout.createSequentialGroup()
			.addComponent(lblPlayerName4)
			.addGap(10, 10, 10)
			.addComponent(txtPlayer4))
		    .addGroup(layout.createSequentialGroup()
			.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			    .addGroup(layout.createSequentialGroup()
				.addComponent(rdBtn2)
				.addGap(18, 18, 18)
				.addComponent(rdBtn3)
				.addGap(18, 18, 18)
				.addComponent(rdBtn4))
			    .addComponent(lblPlayers)
			    .addComponent(lblName)
			    .addComponent(btnConfirm))
			.addGap(0, 49, Short.MAX_VALUE)))
		.addContainerGap())
	);
	layout.setVerticalGroup(
	    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    .addGroup(layout.createSequentialGroup()
		.addContainerGap()
		.addComponent(lblPlayers)
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		    .addComponent(rdBtn2)
		    .addComponent(rdBtn3)
		    .addComponent(rdBtn4))
		.addGap(26, 26, 26)
		.addComponent(lblName)
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		    .addComponent(lblPlayerName1)
		    .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		    .addComponent(lblPlayerName2)
		    .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		    .addComponent(lblPlayerName3)
		    .addComponent(txtPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
		    .addComponent(lblPlayerName4)
		    .addComponent(txtPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		.addComponent(btnConfirm)
		.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	);

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn2ActionPerformed
	txtPlayer1.setEnabled (true);
	txtPlayer2.setEnabled (true);
	txtPlayer3.setEnabled (false);
	txtPlayer4.setEnabled (false);
        txtPlayer3.setText ("");
        txtPlayer4.setText ("");
	playerCount = 2;
    }//GEN-LAST:event_rdBtn2ActionPerformed

    private void rdBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn3ActionPerformed
	txtPlayer1.setEnabled (true);
	txtPlayer2.setEnabled (true);
	txtPlayer3.setEnabled (true);
	txtPlayer4.setEnabled (false);
        txtPlayer4.setText ("");
	playerCount = 3;
    }//GEN-LAST:event_rdBtn3ActionPerformed

    private void rdBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn4ActionPerformed
	txtPlayer1.setEnabled (true);
	txtPlayer2.setEnabled (true);
	txtPlayer3.setEnabled (true);
	txtPlayer4.setEnabled (true);
	playerCount = 4;
    }//GEN-LAST:event_rdBtn4ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
	/*
        Pre: Program has the names of each player and how many people are playing
        Post: Each player is given a "Player" field and the field is filled with their names, perlimenary balance, etc.
        */
        String names [] = {txtPlayer1.getText(), txtPlayer2.getText(), txtPlayer3.getText(), txtPlayer4.getText()};
	for (int i = 0; i < playerCount; i++) {
	    ArrayList<House> temp = new ArrayList<>();
	    Player p = new Player (names[i], temp, 25000000);
	    tempPlayers.add (p);
	}
	
        //Opens main screen where game will be played
	GameScreenApp open = new GameScreenApp ();
	open.setVisible (true);
	close ();
    }//GEN-LAST:event_btnConfirmActionPerformed
    
    public void close () {
	WindowEvent winClosingEvent = new WindowEvent (this, WindowEvent.WINDOW_CLOSING);
	Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(PlayerSelectApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(PlayerSelectApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(PlayerSelectApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(PlayerSelectApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new PlayerSelectApp().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPlayerName1;
    private javax.swing.JLabel lblPlayerName2;
    private javax.swing.JLabel lblPlayerName3;
    private javax.swing.JLabel lblPlayerName4;
    private javax.swing.JLabel lblPlayers;
    private javax.swing.ButtonGroup numPlayers;
    private javax.swing.JRadioButton rdBtn2;
    private javax.swing.JRadioButton rdBtn3;
    private javax.swing.JRadioButton rdBtn4;
    public static javax.swing.JTextField txtPlayer1;
    public static javax.swing.JTextField txtPlayer2;
    public static javax.swing.JTextField txtPlayer3;
    public static javax.swing.JTextField txtPlayer4;
    // End of variables declaration//GEN-END:variables
}
